# Generated by Django 2.2.3 on 2019-07-23 13:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm_admin', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='salesman',
            name='salesMan_id',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
